USE [master]
GO

/****** Object:  Database [DB_121607_nomad]    Script Date: 8/25/2020 2:39:50 PM ******/
CREATE DATABASE [DB_121607_nomad]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_121607_nomad_data', FILENAME = N'e:\sqldata\DB_121607_nomad_data.mdf' , SIZE = 8192KB , MAXSIZE = 25600KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_121607_nomad_log', FILENAME = N'f:\sqllog\DB_121607_nomad_log.ldf' , SIZE = 73728KB , MAXSIZE = 1024000KB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_121607_nomad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_121607_nomad] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_121607_nomad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_121607_nomad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_121607_nomad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_121607_nomad] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_121607_nomad] SET  MULTI_USER 
GO

ALTER DATABASE [DB_121607_nomad] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_121607_nomad] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_121607_nomad] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_121607_nomad] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_121607_nomad] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_121607_nomad] SET QUERY_STORE = ON
GO

ALTER DATABASE [DB_121607_nomad] SET QUERY_STORE (OPERATION_MODE = READ_ONLY, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 3), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DB_121607_nomad] SET  READ_WRITE 
GO

