//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div 
        ///     class=&quot;rec_prim&quot;
        ///     id = &quot;//id//&quot;
        ///     onclick=&quot;//method//&quot;
        ///&gt;
        ///    //nomencl//
        ///    &lt;div
        ///         class=&quot;rec_sub&quot;
        ///         id = &quot;//id//_&quot;
        ///    &gt;
        ///        //summary//
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ht_rec {
            get {
                return ResourceManager.GetString("ht_rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div
        ///     class=&quot;srs&quot;
        ///     onclick=&quot;//method//(//prms//);&quot;
        ///&gt;
        ///    //content//
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ht_srs {
            get {
                return ResourceManager.GetString("ht_srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;text&quot;
        ///       id=&quot;//id//&quot;
        ///       maxlength=&quot;//c_mx//&quot;
        ///       value=&quot;//cur//&quot; /&gt;
        ///
        ///&lt;br /&gt;
        ///
        ///    Max: //c_mx//.
        /// </summary>
        internal static string ht_t_bo {
            get {
                return ResourceManager.GetString("ht_t_bo", resourceCulture);
            }
        }
    }
}
